language: python

env:
  - PYTHON=2.7
  - PYTHON=3.5
  - PYTHON=3.6
  - PYTHON=3.7

install:
    # Install conda
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh  # Python 2.7
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels pandas
    - conda update -q conda
    - conda info -a

    # Install deps
    - conda create -q -n pyenv python=$PYTHON pip
    - source activate pyenv
    - python -m pip install -U pip
    - pip install -r requirements.txt
    - pip install pytest
    - pip install pytest-benchmark
    - pip install .
    # Install solvers for tests.
    - pip install lap scipy ortools
    # lapsolver does not provide a version for python 2
    - pip install "lapsolver; python_version >= '3'"
    # munkres no longer supports python 2
    - pip install "munkres; python_version >= '3'"

script: pytest
